// seed/projects.js — work projects (IDs are stable strings, not random)
export const projects = [
  {
    id: 'p-stock',
    name: 'Stock Trading Platform',
    period: 'Jun 2025 – Nov 2025',
    teamSize: 3,
    role: 'Front-end Lead',
    stack: ['React.js', 'Node.js', 'Express.js', 'WebSockets', 'MongoDB', 'MySQL', 'Keycloak'],
    description: 'Real-time stock trading platform with Option Chain module, market data streaming, 2FA logins.',
    outcomes: [
      'Architected Option Chain from scratch with 2x perf via virtualization, API restructuring, query tuning',
      'Built custom visible-area virtualization reducing DOM load',
      'Designed RESTful APIs (Node + Express)',
      'Optimized MongoDB & MySQL queries',
      'Integrated Keycloak + TOTP for 2FA',
    ],
  },
  {
    id: 'p-docs',
    name: 'Scalable Documentation Platform',
    period: '2025',
    teamSize: 3,
    role: 'Frontend Engineer',
    stack: ['React.js', 'Next.js (App Router)', 'Tailwind CSS', 'TypeScript', 'WebSockets'],
    description: 'Docusaurus-based docs platform with real-time collaborative editing.',
    outcomes: [
      'Scalable Docusaurus platform for knowledge management',
      'Real-time collaborative editing via WebSockets',
      'Pixel-perfect Figma → production',
      'Reusable code editor component with live preview',
    ],
  },
  {
    id: 'p-editor',
    name: 'Dynamic Content Editor (Microfrontend)',
    period: '2024 – 2025',
    teamSize: 2,
    role: 'Senior React Developer',
    stack: ['React.js', 'JavaScript (ES6+)', 'Microfrontend', 'Git'],
    description: 'Real-time webpage element editor in microfrontend architecture.',
    outcomes: [
      'Real-time modification of text, images, links, styles',
      'Undo/Redo, History Management, DOM Picker, Click Tracking',
      'Reusable templates: Back to Top, Coupon Drawer, Progress Bar',
    ],
  },
  {
    id: 'p-maak',
    name: 'Maak — Services Booking App',
    period: '2022 – 2023',
    teamSize: 3,
    role: 'Senior React Native Developer',
    stack: ['React Native', 'Redux', 'REST APIs', 'GraphQL', 'Firebase', 'JWT', 'TypeScript'],
    description: 'Multi-service booking platform with admin panel and mobile app.',
    outcomes: [
      'Booking + secure payment for multi-service platform',
      'Multi-language support',
      'JWT auth, utility bill payments',
    ],
  },
  {
    id: 'p-packarma',
    name: 'Packarma — Packaging Recommendation App',
    period: '2021 – 2022',
    teamSize: 3,
    role: 'Senior React Native Developer',
    stack: ['React Native', 'JavaScript (ES6+)', 'REST APIs', 'GraphQL', 'Firebase', 'JWT', 'Razorpay'],
    description: 'Mobile app recommending laminate packaging by product type, strength, shelf life.',
    outcomes: [
      'Recommendation engine for optimal packaging',
      'Firebase analytics + Razorpay payments',
      'Pixel-perfect Figma → production UI',
    ],
  },
];
